/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Tue Nov 15 11:16:46 2016. */

#include "data.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t DataMessage_fields[29] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, DataMessage, imu_temp, imu_temp, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, DataMessage, imu_magnet_x, imu_temp, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, DataMessage, imu_magnet_y, imu_magnet_x, 0),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, DataMessage, imu_magnet_z, imu_magnet_y, 0),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, DataMessage, imu_gyro_x, imu_magnet_z, 0),
    PB_FIELD(  6, INT32   , OPTIONAL, STATIC  , OTHER, DataMessage, imu_gyro_y, imu_gyro_x, 0),
    PB_FIELD(  7, INT32   , OPTIONAL, STATIC  , OTHER, DataMessage, imu_gyro_z, imu_gyro_y, 0),
    PB_FIELD(  8, UINT32  , OPTIONAL, STATIC  , OTHER, DataMessage, tritium_rx_error_count, imu_gyro_z, 0),
    PB_FIELD(  9, UINT32  , OPTIONAL, STATIC  , OTHER, DataMessage, tritium_tx_error_count, tritium_rx_error_count, 0),
    PB_FIELD( 10, UINT32  , OPTIONAL, STATIC  , OTHER, DataMessage, tritium_active_motor, tritium_tx_error_count, 0),
    PB_FIELD( 11, UINT32  , OPTIONAL, STATIC  , OTHER, DataMessage, tritium_error_flags, tritium_active_motor, 0),
    PB_FIELD( 12, UINT32  , OPTIONAL, STATIC  , OTHER, DataMessage, tritium_limit_flags, tritium_error_flags, 0),
    PB_FIELD( 13, UINT32  , OPTIONAL, STATIC  , OTHER, DataMessage, tritium_bus_current, tritium_limit_flags, 0),
    PB_FIELD( 14, UINT32  , OPTIONAL, STATIC  , OTHER, DataMessage, tritium_bus_voltage, tritium_bus_current, 0),
    PB_FIELD( 15, UINT32  , OPTIONAL, STATIC  , OTHER, DataMessage, tritium_phase_current, tritium_bus_voltage, 0),
    PB_FIELD( 16, FLOAT   , OPTIONAL, STATIC  , OTHER, DataMessage, tritium_15v_rail, tritium_phase_current, 0),
    PB_FIELD( 17, FLOAT   , OPTIONAL, STATIC  , OTHER, DataMessage, tritium_3v3, tritium_15v_rail, 0),
    PB_FIELD( 18, FLOAT   , OPTIONAL, STATIC  , OTHER, DataMessage, tritium_1v9, tritium_3v3, 0),
    PB_FIELD( 19, FLOAT   , OPTIONAL, STATIC  , OTHER, DataMessage, tritium_motor_temp, tritium_1v9, 0),
    PB_FIELD( 20, FLOAT   , OPTIONAL, STATIC  , OTHER, DataMessage, tritium_heatsink_temp, tritium_motor_temp, 0),
    PB_FIELD( 21, FLOAT   , OPTIONAL, STATIC  , OTHER, DataMessage, tritium_dsp_temp, tritium_heatsink_temp, 0),
    PB_FIELD( 22, FLOAT   , OPTIONAL, STATIC  , OTHER, DataMessage, tritium_dc_bus_amphour, tritium_dsp_temp, 0),
    PB_FIELD( 23, FLOAT   , OPTIONAL, STATIC  , OTHER, DataMessage, tritium_odometer, tritium_dc_bus_amphour, 0),
    PB_FIELD( 24, BOOL    , OPTIONAL, STATIC  , OTHER, DataMessage, tritiums_on, tritium_odometer, 0),
    PB_FIELD( 25, INT32   , OPTIONAL, STATIC  , OTHER, DataMessage, average_speed, tritiums_on, 0),
    PB_FIELD( 26, INT32   , OPTIONAL, STATIC  , OTHER, DataMessage, drive_mode, average_speed, 0),
    PB_FIELD( 27, INT32   , OPTIONAL, STATIC  , OTHER, DataMessage, cruise_speed, drive_mode, 0),
    PB_FIELD( 28, BOOL    , OPTIONAL, STATIC  , OTHER, DataMessage, cruise_on, cruise_speed, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
